---
- name: Instalar BIND9
  apt:
    name:
      - bind9
      - bind9utils
    state: present
    update_cache: yes

- name: Configurar IPv6 est치tica en Netplan
  template:
    src: netplan.yaml.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: '0644'

- name: Aplicar configuraci칩n de red
  command: netplan apply
  changed_when: false

- name: Crear directorio de zonas
  file:
    path: /var/cache/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: '0755'

- name: Copiar clave TSIG
  template:
    src: ../../templates/tsig.key.j2
    dest: /etc/bind/tsig.key
    owner: bind
    group: bind
    mode: '0640'

- name: Configurar named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: '0644'
  notify: restart bind9

- name: Configurar named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: '0644'
  notify: restart bind9

- name: Permitir tr치fico DNS (UDP)
  ufw:
    rule: allow
    port: '53'
    proto: udp
    comment: 'Allow DNS queries'

- name: Permitir tr치fico DNS (TCP)
  ufw:
    rule: allow
    port: '53'
    proto: tcp
    comment: 'Allow DNS queries'

- name: Iniciar y habilitar BIND9
  systemd:
    name: bind9
    state: started
    enabled: yes
